### ISSUE TITLE
Guildelines for code style

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Organization#14]
- See https://github.com/invenia/BlueStyle
- Create a README with the differences to what we actually want to do (e.g. 2 spaces)
- Update packages not doing it

**Comment by dpo** [comment]
Here's another, simpler, one: https://github.com/jrevels/YASGuide

**Comment by abelsiqueira** [comment]
We have an implicit style going on, and not enough style issues. Closing for now.
