### ISSUE TITLE
License

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Organization#3]
For the License discussion.

Possibilities
- GPL
- LGPL
- MIT
- MPL (Mozilla)

Questions:
- [ ] How is MPL different from LGPL

**Comment by abelsiqueira** [comment]
Quick summaries from TLDRlegal

[GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))
You may copy, distribute and modify the software as long as you track changes/dates in source files. Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

[LGPLv3](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3))
This license is mainly applied to libraries. You may copy, distribute and modify the software provided that modifications are described and licensed for free under LGPL. Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be.

[MPLv2](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))
MPL is a copyleft license that is easy to comply with. You must make the source code for any of your changes available under MPL, but you can combine the MPL software with proprietary code, as long as you keep the MPL code in separate files. Version 2.0 is, by default, compatible with LGPL and GPL version 2 or greater. You can distribute binaries under a proprietary license, as long as you make the source available under MPL.

[MIT](https://tldrlegal.com/license/mit-license)
A short, permissive software license. Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source.  There are many variations of this license in use.

**Comment by abelsiqueira** [comment]
My opinions, in the order of preference for our packages.

- MPL allows use in closed proprietary software but requires modifications to be released. Seems to be a good middle ground.
- GPL is very restrictive but it may be adequate for a few packages. In particular, if the package is solely focused on research (e.g. CUTEst).
- LGPL is similar to MPL but it restricts more on the way the software is used by other software. Since the notion is not very clear to me, I prefer using MPL.
- MIT is too permissive. It is the Julia default, but I don't see a good reason to use it, instead of using MPL.

**Comment by dpo** [comment]
Thanks @abelsiqueira ! How does it work when the Julia package is an interface to a library that already has a certain license?

**Comment by abelsiqueira** [comment]
It appears that
- if we don't ship nor build the library, there seems to be no restriction (See e.g. Gurobi, CPLEX, Knitro, Mosek from JuliaOpt, all using MIT);
- if we don't ship but build/download the library/binaries, it seems to depend on the license. GPL seems to require GPL, but the others appear to be less restrictive.
Ipopt and Cbc use EPL, which is similar to LGPL. Both Ipopt.jl and Cbc.jl are on MIT.
GLPK and GLPK.jl use GPL.

It might be easier to use MIT for proprietary and BSD-licensed libraries (e.g. HSL.jl and SuiteSparse related) and LGPL for LGPL (e.g. CUTEst).
