### ISSUE TITLE
Spacing style

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Organization#8]
Though there is some discussion about an official style guide, it seems like 4 spaces is the default indentation used in Julia. Though it pains me to consider the size of the change, should we change it?
cc @dpo @vepiteski @Xx-fractale-xX

**Comment by dpo** [comment]
I find that 4 spaces is a lot and if you have a few nested structures, you quickly reach the right-hand side of your screen or editor. I'd rather we add functionality than perform this kind of stylistic change. Python's PEP8 also recommended 4 spaces but the linters allowed you to change that value. I personally prefer 2 spaces.
